# file.yml
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
christmas: true
french_hens: 3
calling_birds:
  - huey
  - dewey
  - louie
  - fred
christmas_fifth_day:
  calling_birds: four
  french_hens: 3
  golden_rings: 5
  partridges:
    count: 1
    location: "a pear tree"
  turtle_doves: two
  