Do: "A deer, a female deer."
Re: "A drop of golden sun."
Mi: "A name I call myself."
Fa: "A long long way to run."
So: "A needle pulling thread."
La: "A note to follow so."
Ti: "A drink with jam and bread."